"""Checks of Proposition 7 of the theory supplement: what Anam's kernel does with a noisy open.

POST HOC. The proposition was derived after the independent audit of 9 October 2026 (items A04 and A05;
``audits/2026-10-09_research_audit.md``). It turns two of the audit's objections into results:

* the kernel's overnight term (b o)^2 understates the efficient overnight second moment;
* the extended range cannot remove an opening error that already sets the high or the low.

It then measures, under the supplement's Assumption 2, how much of the opening error's variance each
kernel absorbs. Nothing here is a test of a prediction, and no frozen verdict depends on it.

Part A  Every closed form, identity and inequality of Proposition 7 is set against a simulation, a
        numerical integral or a pathwise identity (ledger: table133).
Part B  Each kernel's exposure to the opening error, exactly (by simulation) at realistic error sizes,
        beside the first-order loadings (table134).
Part C  The scale of the efficient overnight move, s = sigma_o*/sigma_c, and of the error, rho, that
        each sample's moments imply under an uncorrelated error, with the first-order loadings at that s
        (reported only; table134).

Every number the LaTeX quotes is written as a macro to paper/theory/generated/kernel.tex, and the
loadings table to generated/tab_kernel.tex.

Usage
    python scripts/48_kernel_theory.py            # Parts A-C (a few minutes; Part C reads the frontier panels)
    python scripts/48_kernel_theory.py --quick    # Parts A and B with smaller simulations, no Part C
"""
from __future__ import annotations

from _env import bootstrap

ROOT = bootstrap(["scipy"])

import argparse
import importlib.util
import math
import time

import numpy as np
import pandas as pd
from scipy import integrate
from scipy.stats import norm

TAB = ROOT / "output" / "tables"
GEN = ROOT / "paper" / "theory" / "generated"
INPUTS = ROOT / "data" / "external" / "frontier"
SEED = 20261011
LN2 = math.log(2.0)
LAM0 = 0.2
FLOAT_FMT = "%.10g"
SQ2PI = math.sqrt(2.0 * math.pi)


def _load(name: str, file: str):
    spec = importlib.util.spec_from_file_location(name, ROOT / "scripts" / file)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


s45 = _load("s45_for_48", "45_theory_checks.py")
Ledger, batch_mean, brownian_bars, p_max_min = s45.Ledger, s45.batch_mean, s45.brownian_bars, s45.p_max_min


class Numbers(s45.Numbers):
    def write(self, path) -> None:
        lines = ["% Generated by scripts/48_kernel_theory.py -- do not edit by hand.",
                 "% The numbers of Proposition 7 and its table."]
        for k in sorted(self.m):
            lines.append(r"\expandafter\def\csname thn@" + k + r"\endcsname{" + self.m[k] + "}")
        path.write_text("\n".join(lines) + "\n")


# =============================================================================================
# Closed forms
# =============================================================================================

def meander_cdf(u: float, K: int = 60) -> float:
    """P(U <= u) for the maximum U of a Brownian meander on [0, 1]: 1 + 2 sum (-1)^k exp(-k^2 u^2 / 2),
    or, for small u, its Jacobi-transformed form (2 sqrt(2 pi) / u) sum_k exp(-(2k+1)^2 pi^2 / (2 u^2))."""
    if u <= 0:
        return 0.0
    if u < 1.0:
        k = np.arange(K)
        return float(2.0 * SQ2PI / u * np.sum(np.exp(-((2 * k + 1) ** 2) * math.pi ** 2 / (2.0 * u * u))))
    k = np.arange(1, K + 1)
    return float(1.0 + 2.0 * np.sum((-1.0) ** k * np.exp(-(k ** 2) * u * u / 2.0)))


def meander_mean() -> float:
    return integrate.quad(lambda u: 1.0 - meander_cdf(u), 0.0, 12.0, limit=400, epsabs=1e-13)[0]


def psi(a):
    """E[(Z - a)^+] = phi(a) - a Phibar(a)."""
    return norm.pdf(a) - a * norm.sf(a)


def gamma_tr(s: float) -> float:
    """First-order loading of TR^2/(4 ln 2): 1/4 + s/(4 pi ln 2) - I(s)/(2 sqrt(2 pi) ln 2), where
    I(s) = int_0^inf Phibar(u/s) P(U > u) du."""
    if s <= 0:
        return 0.25
    # I(s) = int_0^inf Phibar(u/s) P(U > u) du: for s < 1 integrate in v = u/s, so that the narrow
    # factor Phibar(u/s) is resolved; for s >= 1 in u, where the narrow factor is P(U > u)
    if s < 1.0:
        I = s * integrate.quad(lambda v: norm.sf(v) * (1.0 - meander_cdf(s * v)), 0.0, 40.0, limit=400,
                               epsabs=1e-14)[0]
    else:
        I = integrate.quad(lambda u: norm.sf(u / s) * (1.0 - meander_cdf(u)), 0.0, 12.0, limit=400,
                           epsabs=1e-14)[0]
    return 0.25 + s / (4.0 * math.pi * LN2) - I / (2.0 * SQ2PI * LN2)


def gamma_tr_direct(s: float) -> float:
    """The same loading from its definition, 1/4 + s E[psi(U/s)] / (2 sqrt(2 pi) ln 2), integrating psi
    against the meander density (a second numerical route)."""
    dens = lambda u: (meander_cdf(u + 1e-5) - meander_cdf(u - 1e-5)) / 2e-5
    E = integrate.quad(lambda u: psi(u / s) * dens(u), 1e-4, 12.0, limit=600, epsabs=1e-12)[0]
    return 0.25 + s * E / (2.0 * SQ2PI * LN2)


def meander_cdf_from_images(x: float, a: float = 1e-4) -> float:
    """P(-m <= x | M < a) for small a, from the method-of-images series: the meander limit of the
    supplement's equation (G)."""
    return p_max_min(a, x) / (2.0 * norm.cdf(a) - 1.0)


# =============================================================================================
# The kernels on simulated bars (Assumption 2, with o* ~ N(0, s^2) and sigma_c = 1)
# =============================================================================================

def kernels(ostar, eta, M, m, D, s, rho, lam0=LAM0):
    """Each kernel on the printed bar, and on the bar without the error, per draw."""
    o = ostar + eta
    h, l = ostar + np.maximum(eta, M), ostar + np.minimum(eta, m)
    he, le = ostar + M, ostar + m
    r = ostar + D
    b = s * s / (s * s + rho * rho)
    w = lam0 * (1.0 - b)
    R, Re = h - l, M - m
    TR, TRe = np.maximum(h, 0) - np.minimum(l, 0), np.maximum(he, 0) - np.minimum(le, 0)
    Rs = np.maximum(h, b * o) - np.minimum(l, b * o)
    P, Pe = R ** 2 / (4 * LN2), Re ** 2 / (4 * LN2)
    TP, TPe = TR ** 2 / (4 * LN2), TRe ** 2 / (4 * LN2)
    full = (1 - w) * ((b * o) ** 2 + Rs ** 2 / (4 * LN2)) + w * r * r
    post = (1 - w) * (b * b * o * o + b * (1 - b) * (s * s + rho * rho) + Rs ** 2 / (4 * LN2)) + w * r * r
    clean = ostar ** 2 + Pe                                  # every full-type kernel when the open is exact
    return {
        "close-to-close r^2": (r * r, r * r),
        "Parkinson": (P, Pe),
        "true-range Parkinson TR^2/(4 ln 2)": (TP, TPe),
        "open-free kernel": ((1 - lam0) * TP + lam0 * r * r, (1 - lam0) * TPe + lam0 * r * r),
        "full kernel": (full, clean),
        "full kernel, posterior overnight term": (post, clean),
        "overnight^2 + Parkinson": (o * o + P, clean),
    }


FIRST_ORDER = {"close-to-close r^2": lambda s: 0.0, "Parkinson": lambda s: 0.5,
               "true-range Parkinson TR^2/(4 ln 2)": gamma_tr, "open-free kernel": lambda s: (1 - LAM0) * gamma_tr(s),
               "full kernel": lambda s: -0.5, "full kernel, posterior overnight term": lambda s: 0.5,
               "overnight^2 + Parkinson": lambda s: 1.5}


# =============================================================================================
# Part A
# =============================================================================================

def part_a(L: Ledger, N: Numbers, n: int, steps: int, rng) -> dict:
    P = "7"
    # (a) the overnight term -------------------------------------------------------------------
    for s, t in ((1.0, 0.8), (0.5, 1.2), (2.0, 0.5)):
        os_ = rng.normal(0, s, n)
        o = os_ + rng.normal(0, t, n)
        b = s * s / (s * s + t * t)
        m2 = s * s + t * t
        v, se = batch_mean((b * o) ** 2 - b * os_ ** 2)
        L.mc(P, "a: E[(b o)^2] = b E[o*^2] under an uncorrelated error", f"s={s}, sigma_eta={t}", 0.0, v, se)
        v, se = batch_mean(b * b * o * o + b * (1 - b) * m2 - os_ ** 2)
        L.mc(P, "a: the linear posterior moment is unbiased for E[o*^2]", f"s={s}, sigma_eta={t}", 0.0, v, se)
        # Gaussian conditional second moment: regress o*^2 on o^2 (slope b^2, intercept (1-b) s^2)
        X = np.column_stack([np.ones(n), o * o])
        coef = np.linalg.lstsq(X, os_ ** 2, rcond=None)[0]
        resid = os_ ** 2 - X @ coef
        cov = np.linalg.inv(X.T @ X) * np.mean(resid ** 2)
        L.mc(P, "a: Gaussian E[o*^2 | o] has slope b^2 on o^2", f"s={s}, sigma_eta={t}", b * b, coef[1],
             math.sqrt(cov[1, 1]))
        L.mc(P, "a: Gaussian E[o*^2 | o] has intercept b(1-b)E[o^2]", f"s={s}, sigma_eta={t}", b * (1 - b) * m2,
             coef[0], math.sqrt(cov[0, 0]))
    for theta in (0.5, 2.0):
        os_ = rng.normal(0, 1.0, n)
        o = (1 + theta) * os_
        b = float(np.mean(o * os_) / np.mean(o * o))
        L.ident(P, "a: proportional overreaction makes (b o)^2 = o*^2 pathwise", f"theta={theta}",
                0.0, float(np.max(np.abs((b * o) ** 2 - os_ ** 2))), tol=1e-9)
    # the deficit is not identified: two laws with the same (o, r) law, different E[o*^2]
    moo, mrr, b = 1.0, 2.0, 0.4
    low, high = b * b * moo, mrr
    L.holds(P, "a: (b o)^2 has the same mean under every law of Prop. 1(e)", "E[o^2]=1, E[r^2]=2, b=0.4",
            b * b * moo, b * b * moo, True, "E[(b o)^2] = b^2 E[o^2] depends only on the law of (o, r)")
    L.holds(P, "a: the deficit spans [0, E[r^2] - b^2 E[o^2]]", "E[o^2]=1, E[r^2]=2, b=0.4", high - low,
            high - low, high > low, "E[o*^2] - b^2 E[o^2] = 0 and = E[r^2] - b^2 E[o^2] are both attained")

    # (b) the extended range, pathwise ------------------------------------------------------------
    o = rng.normal(0, 0.02, n)
    c = rng.normal(0, 0.02, n)
    u = np.maximum(0, c) + rng.exponential(0.01, n)
    d = np.minimum(0, c) - rng.exponential(0.01, n)
    h, l = o + u, o + d
    for bval in (0.0, 0.3, 0.7, 1.0):
        bo = bval * o
        Rs = (u - d) + np.maximum(0, bo - h) + np.maximum(0, l - bo)
        alt = np.maximum(h, bo) - np.minimum(l, bo)
        TR = np.maximum(h, 0) - np.minimum(l, 0)
        L.ident(P, "b: R* = max(h, b o) - min(l, b o)", f"b={bval}, {n} bars", 0.0, float(np.max(np.abs(Rs - alt))),
                tol=1e-12)
        L.holds(P, "b: R <= R* <= TR", f"b={bval}, {n} bars", 0.0,
                float(np.sum((Rs < (u - d) - 1e-15) | (Rs > TR + 1e-15))),
                bool(np.all((Rs >= (u - d) - 1e-15) & (Rs <= TR + 1e-15))), "violations = 0")
    L.ident(P, "b: R* = R when b = 1", f"{n} bars", 0.0,
            float(np.max(np.abs((np.maximum(h, o) - np.minimum(l, o)) - (u - d)))), tol=1e-12)
    ex = math.log(1.05)
    ex_kernel = (1 - LAM0) * ex ** 2 / (4 * LN2)
    L.ident(P, "b: the audit's bar gives R* = ln(O/C_-)", "C_- = C = L = 100, O = H = 105, b = 0", ex,
            float(np.maximum(ex, 0.0) - np.minimum(0.0, 0.0)))
    N.put("k7-ex-kernel", ex_kernel * 1e4, nd=2)

    # (c) the meander law and the loading -----------------------------------------------------------
    EU = meander_mean()
    L.numeric(P, "c: E[U] = sqrt(2 pi) ln 2 from the meander law", "integral of 1 - F_U", SQ2PI * LN2, EU, tol=1e-9)
    N.put("k7-EU", EU, nd=4)
    for x in (0.5, 1.0, 1.5, 2.0, 3.0):
        L.numeric(P, "c: the meander law is the images limit of (-m | M < a)", f"x={x}, a=1e-4",
                  meander_cdf(x), meander_cdf_from_images(x), tol=2e-4)
        if x >= 1.0:
            k = np.arange(1, 61)
            L.numeric(P, "c: both forms of the meander law agree", f"x={x}", meander_cdf(x),
                      float(2.0 * SQ2PI / x * np.sum(np.exp(-((2 * np.arange(60) + 1) ** 2) * math.pi ** 2 / (2 * x * x)))),
                      tol=1e-12)
            _ = k
    grid = np.linspace(0.05, 6.0, 60)
    g = np.array([gamma_tr(s) for s in grid])
    L.holds(P, "c: gamma_TR is increasing in s", "s in [0.05, 6], 60 points", float(np.min(np.diff(g))), 0.0,
            bool(np.all(np.diff(g) > 0)), "min increment > 0")
    lo = np.maximum(0.25, grid / (4 * math.pi * LN2))
    hi = 0.25 + grid / (4 * math.pi * LN2)
    L.holds(P, "c: max(1/4, s/(4 pi ln 2)) <= gamma_TR <= 1/4 + s/(4 pi ln 2)", "s in [0.05, 6], 60 points",
            float(np.min(np.minimum(g - lo, hi - g))), 0.0, bool(np.all((g >= lo - 1e-12) & (g <= hi + 1e-12))),
            "both margins >= 0")
    L.numeric(P, "c: gamma_TR -> 1/4 as s -> 0", "s = 1e-3", 0.25, gamma_tr(1e-3), tol=1e-6)
    L.numeric(P, "c: gamma_TR - s/(4 pi ln 2) -> 0 as s -> infinity", "s = 200", 0.0,
              gamma_tr(200.0) - 200.0 / (4 * math.pi * LN2), tol=5e-3)
    for s in (0.25, 0.5, 1.0, 2.0, 4.0):
        L.numeric(P, "c: two routes to gamma_TR agree", f"s={s}", gamma_tr(s), gamma_tr_direct(s), tol=2e-4)
    for s in (0.3, 0.5, 1.0, 2.0):
        key = str(s).replace(".", "p")
        N.put(f"k7-gTR-{key}", gamma_tr(s), nd=3)
        N.put(f"k7-gOF-{key}", (1 - LAM0) * gamma_tr(s), nd=3)

    # first-order loadings against simulation: paired draws, extrapolated linearly in rho to zero
    D, M, m = brownian_bars(n, steps, rng)
    Z1, Z2 = rng.standard_normal(n), rng.standard_normal(n)
    rhos = (0.02, 0.04, 0.08)
    names = ("Parkinson", "true-range Parkinson TR^2/(4 ln 2)", "open-free kernel", "full kernel",
             "full kernel, posterior overnight term", "overnight^2 + Parkinson")
    for s in (0.5, 1.0, 2.0):
        fits = {name: ([], []) for name in names}
        for rho in rhos:
            ks = kernels(s * Z1, rho * Z2, M, m, D, s, rho)
            for name in names:
                v, se = batch_mean((ks[name][0] - ks[name][1]) / rho ** 2)
                fits[name][0].append(v)
                fits[name][1].append(se)
            del ks
        for name in names:
            est, ses = fits[name]
            # weighted least squares of the loading on rho; the intercept is the first-order loading
            Wt = 1.0 / np.square(ses)
            X = np.column_stack([np.ones(3), rhos])
            A = X.T @ (X * Wt[:, None])
            beta = np.linalg.solve(A, X.T @ (Wt * np.array(est)))
            se0 = math.sqrt(np.linalg.inv(A)[0, 0])
            L.mc(P, f"c: first-order loading of the {name}", f"s={s}, rho={rhos}, {n} paths, {steps} steps",
                 FIRST_ORDER[name](s), beta[0], se0)
    return dict(D=D, M=M, m=m, Z1=Z1, Z2=Z2)


# =============================================================================================
# Part B: exact exposures
# =============================================================================================

def part_b(draws: dict) -> pd.DataFrame:
    rows = []
    for s in (0.3, 0.5, 1.0, 2.0):
        for rho in (0.25, 0.5, 1.0):
            ks = kernels(s * draws["Z1"], rho * draws["Z2"], draws["M"], draws["m"], draws["D"], s, rho)
            for name, (k, k0) in ks.items():
                v, se = batch_mean((k - k0) / rho ** 2)
                rows.append(dict(part="B", sample="Assumption 2", s=s, rho=rho, kernel=name,
                                 first_order_loading=FIRST_ORDER[name](s), exact_loading=v, se=se,
                                 relative_bias=float(np.mean(k - k0) / np.mean(k0))))
    return pd.DataFrame(rows)


# =============================================================================================
# Part C: the scales the data imply, under an uncorrelated error
# =============================================================================================

def implied(b: float, ratio: float) -> tuple[float, float]:
    """(s, rho) from b and E[o^2]/E[c^2] when E[o* eta] = 0 and closing errors are zero:
    sigma_eta^2 = (1 - b) E[o^2], sigma_c^2 = E[c^2] - sigma_eta^2, E[o*^2] = b E[o^2]."""
    x = (1.0 - b) * ratio
    s2 = b * ratio / (1.0 - x)
    return math.sqrt(s2), math.sqrt(x / (1.0 - x))


def part_c(draws: dict) -> pd.DataFrame:
    rows = []
    ap = pd.read_csv(TAB / "table122_theory_applications.csv")
    for reg in ("A1", "B", "A2", "C"):
        x = ap[(ap.part == "B1") & (ap["sample"] == f"NEPSE {reg}")].set_index("statistic")["value"]
        rows.append((f"NEPSE {reg}", float(x["b"]), float(x["E[o^2]/E[OC]"])))
    x = ap[(ap.part == "B1") & ap["sample"].str.startswith("NIFTY")].set_index("statistic")["value"]
    rows.append(("NIFTY 50", float(x["b"]), float(x["E[o^2]/E[OC]"])))
    if INPUTS.exists():
        from nepsevol import frontier as F
        for name in list(F.SPANS) + list(F.SPANS_M18):
            p, _ = F.market_panel(name, INPUTS)
            b = float((p["o"] * p["r"]).sum() / (p["o"] ** 2).sum())
            rows.append((name, b, float((p["o"] ** 2).mean() / (p["c"] ** 2).mean())))
    out = []
    for name, b, ratio in rows:
        if not (0 < b < 1):
            out.append(dict(part="C", sample=name, b=b, ratio=ratio, s=np.nan, rho=np.nan))
            continue
        s, rho = implied(b, ratio)
        row = dict(part="C", sample=name, b=b, ratio=ratio, s=s, rho=rho, gamma_TR=gamma_tr(s),
                   gamma_open_free=(1 - LAM0) * gamma_tr(s))
        # the exact exposures at this sample's own (s, rho)
        ks = kernels(s * draws["Z1"], rho * draws["Z2"], draws["M"], draws["m"], draws["D"], s, rho)
        for name_k, key in (("Parkinson", "exact_P"), ("open-free kernel", "exact_open_free"),
                            ("full kernel", "exact_full"), ("overnight^2 + Parkinson", "exact_o2P")):
            k, k0 = ks[name_k]
            row[key] = float(np.mean(k - k0) / rho ** 2)
        out.append(row)
    return pd.DataFrame(out)


# =============================================================================================
# Output
# =============================================================================================

def fmt(v, nd=3):
    s = f"{abs(v):.{nd}f}"
    return (r"\ensuremath{-}" + s) if v < 0 and float(s) != 0 else s


def write_table(N: Numbers, B: pd.DataFrame) -> None:
    order = ["close-to-close r^2", "Parkinson", "true-range Parkinson TR^2/(4 ln 2)", "open-free kernel",
             "full kernel", "full kernel, posterior overnight term", "overnight^2 + Parkinson"]
    label = {"close-to-close r^2": r"close-to-close $r^2$", "Parkinson": r"Parkinson $R^2/(4\ln2)$",
             "true-range Parkinson TR^2/(4 ln 2)": r"true range $TR^2/(4\ln2)$",
             "open-free kernel": r"open-free kernel $A_0$", "full kernel": r"full kernel $A$",
             "full kernel, posterior overnight term": r"$A$ with $\pi(o)$ for $(b o)^2$",
             "overnight^2 + Parkinson": r"$o^2+P$"}
    lines = []
    for name in order:
        cells = [label[name]]
        for s in (0.3, 1.0):
            cells.append(fmt(FIRST_ORDER[name](s)))
            for rho in (0.5, 1.0):
                r = B[(B.kernel == name) & (B.s == s) & (B.rho == rho)].iloc[0]
                cells.append(fmt(r.exact_loading))
        lines.append(" & ".join(cells) + r" \\")
    (GEN / "tab_kernel.tex").write_text("\n".join(lines) + "\n")
    for name, key in (("Parkinson", "P"), ("open-free kernel", "OF"), ("full kernel", "full"),
                      ("full kernel, posterior overnight term", "post")):
        for s in (0.3, 1.0):
            for rho in (0.5, 1.0):
                r = B[(B.kernel == name) & (B.s == s) & (B.rho == rho)].iloc[0]
                N.put(f"k7-ex-{key}-s{str(s).replace('.', 'p')}-r{str(rho).replace('.', 'p')}", r.exact_loading)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--quick", action="store_true")
    a = ap.parse_args()
    rng = np.random.default_rng(SEED)
    n, steps = (400_000, 50) if a.quick else (4_000_000, 100)
    t0 = time.time()
    L, N = Ledger(), Numbers()
    draws = part_a(L, N, n, steps, rng)
    print(f"  Part A: {time.time() - t0:.0f}s")
    B = part_b(draws)
    led = L.frame()
    led.to_csv(TAB / ("table133_theory_kernel_checks.csv" if not a.quick else "table133_quick.csv"),
               index=False, float_format=FLOAT_FMT)
    N.put("k7-checks-n", str(len(led)))
    N.put("k7-checks-pass", str(int(led["pass"].sum())))
    write_table(N, B)
    if not a.quick:
        C = part_c(draws)
        for r in C.itertuples():
            key = r.sample.replace("NEPSE ", "N").replace(" ", "").replace("-", "")
            if np.isfinite(r.s):
                N.put(f"k7-s-{key}", r.s, nd=2)
                N.put(f"k7-rho-{key}", r.rho, nd=2)
                N.put(f"k7-gOF-{key}", r.gamma_open_free, nd=3)
                N.put(f"k7-xOF-{key}", r.exact_open_free, nd=2)
                N.put(f"k7-xP-{key}", r.exact_P, nd=2)
                N.put(f"k7-xfull-{key}", r.exact_full, nd=2)
        ok = C["s"].notna()
        N.put("k7-xOF-min", C.loc[ok, "exact_open_free"].min(), nd=2)
        N.put("k7-xOF-max", C.loc[ok, "exact_open_free"].max(), nd=2)
        N.put("k7-xP-min", C.loc[ok, "exact_P"].min(), nd=2)
        N.put("k7-xP-max", C.loc[ok, "exact_P"].max(), nd=2)
        N.put("k7-xfull-min", C.loc[ok, "exact_full"].min(), nd=2)
        N.put("k7-xfull-max", C.loc[ok, "exact_full"].max(), nd=2)
        out = pd.concat([B, C], ignore_index=True)
        out.to_csv(TAB / "table134_theory_kernel_exposure.csv", index=False, float_format=FLOAT_FMT)
        N.write(GEN / "kernel.tex")
    fails = led[~led["pass"]]
    print(f"  {len(led)} checks, {int(led['pass'].sum())} pass; {time.time() - t0:.0f}s")
    if len(fails):
        print(fails[["check", "design", "theory", "value", "se"]].to_string(index=False))
    print(B[B.rho == 0.5].pivot_table(index="kernel", columns="s", values="exact_loading").round(3).to_string())
    if not a.quick:
        print(C.to_string(index=False))


if __name__ == "__main__":
    main()
