"""Checks of Proposition 8 of the theory supplement: the market-implied open.

Derived during the development of Anam II (``ANAM2_DEVELOPMENT.md``), from its descriptive round E0, and written
after plan M22 was frozen. It predicts nothing that M22 tests, and no verdict depends on it.

Part A  Every closed form, identity and inequality of Proposition 8 is set against a simulation, a numerical
        computation or a pathwise identity (ledger: table143):
        (a) the leave-one-out market move carries none of the security's own opening error;
        (b) its sampling error has second moment V_N = (N-1)^-2 sum_{j != i} E[(zeta_j + eta_j)^2];
        (c) E[m^2] = beta_bar^2 sigma_f^2 + V_N, and the pooled projection of r on m;
        (d) b = mu + (1 - mu) b_I in the population, and exactly mu_hat b_M_hat + (1 - mu_hat) b_I_hat in a
            sample when the market move is the inclusive cross-sectional mean;
        (e) the kernel on a stale bar and on a bar whose open moved;
        (f) lambda_n, the expected squared range of n equally spaced observations from the anchor: 1 at n = 1,
            increasing, tending to 4 ln 2.
Part B  The data, on each panel's training span (table144): b, its market and stock-specific parts, the market's
        share of the overnight second moment, the attenuation of the leave-one-out projection that (c) predicts
        from the cross-sectional dispersion, and the shares of stale opens and one-price bars.

Every number the LaTeX quotes is written as a macro to paper/theory/generated/market_open.tex, and the data table
to generated/tab_market_open.tex.

Usage
    python scripts/54_market_open_theory.py            # Parts A and B (Part B reads the frontier panels)
    python scripts/54_market_open_theory.py --quick    # Part A with smaller simulations, no Part B
"""
from __future__ import annotations

from _env import bootstrap

ROOT = bootstrap(["scipy"])

import argparse
import importlib.util
import math
import sys
import time

import numpy as np
import pandas as pd

TAB = ROOT / "output" / "tables"
GEN = ROOT / "paper" / "theory" / "generated"
SEED = 20261012
LN2 = math.log(2.0)
FLOAT_FMT = "%.10g"


def _load(name: str, file: str):
    spec = importlib.util.spec_from_file_location(name, ROOT / "scripts" / file)
    mod = importlib.util.module_from_spec(spec)
    argv, sys.argv = sys.argv, sys.argv[:1]
    spec.loader.exec_module(mod)
    sys.argv = argv
    return mod


s45 = _load("s45_for_54", "45_theory_checks.py")
Ledger = s45.Ledger

from nepsevol.estimators import anam as AN  # noqa: E402
from nepsevol.estimators import anam2 as A2  # noqa: E402


class Numbers(s45.Numbers):
    def write(self, path) -> None:
        lines = ["% Generated by scripts/54_market_open_theory.py -- do not edit by hand.",
                 "% The numbers of Proposition 8 and its table."]
        for k in sorted(self.m):
            lines.append(r"\expandafter\def\csname thn@" + k + r"\endcsname{" + self.m[k] + "}")
        path.write_text("\n".join(lines) + "\n")


def panel_draws(rng, N, R, beta, s_f=1.0, s_z=None, s_e=None, rho_ze=0.0):
    """R independent dates of an N-security panel: o_i = beta_i f + zeta_i + eta_i, r_i = beta_i f + zeta_i + x_i,
    with x_i = a common intraday part plus an own part, independent of everything known at the open."""
    s_z = np.full(N, 2.0) if s_z is None else np.asarray(s_z, float)
    s_e = np.full(N, 2.0) if s_e is None else np.asarray(s_e, float)
    f = rng.standard_normal((R, 1)) * s_f
    a = rng.standard_normal((R, N))
    zeta = s_z * a
    eta = s_e * (rho_ze * a + math.sqrt(1.0 - rho_ze ** 2) * rng.standard_normal((R, N)))
    x = 1.5 * rng.standard_normal((R, N)) + 0.7 * rng.standard_normal((R, 1))
    o = beta * f + zeta + eta
    r = beta * f + zeta + x
    m = (o.sum(axis=1, keepdims=True) - o) / (N - 1)
    return dict(f=f, zeta=zeta, eta=eta, x=x, o=o, r=r, m=m)


def lambda_n(rng, n: int, reps: int) -> tuple[float, float]:
    """E[(max(0, W_1..W_n) - min(0, W_1..W_n))^2] for a standard Brownian motion observed at k/n, and its SE."""
    out = []
    left = reps
    while left > 0:
        k = min(left, max(1, 4_000_000 // n))
        W = np.cumsum(rng.standard_normal((k, n)) / math.sqrt(n), axis=1)
        R = np.maximum(W.max(axis=1), 0.0) - np.minimum(W.min(axis=1), 0.0)
        out.append(R * R)
        left -= k
    v = np.concatenate(out)
    return float(v.mean()), float(v.std() / math.sqrt(len(v)))


def part_a(L: Ledger, N: Numbers, R: int, rng) -> None:
    P = "8"
    # (a) no own-error loading
    n = 30
    beta = rng.uniform(0.5, 1.5, n)
    D = panel_draws(rng, n, R, beta, rho_ze=0.4)
    rep = np.mean(D["m"] * D["eta"], axis=1)
    L.mc(P, "(a) E[m_-i eta_i] = 0", f"N={n}, corr(zeta, eta)=0.4, {R:,} dates", 0.0, rep.mean(), rep.std() / math.sqrt(R))
    a0, e0 = D["m"][:, 0] ** 2, D["eta"][:, 0] ** 2
    prod = (a0 - a0.mean()) * (e0 - e0.mean())
    L.mc(P, "(a) Cov(m_-i^2, eta_i^2) = 0", f"N={n}, security 0", 0.0, prod.mean(), prod.std() / math.sqrt(R))
    o2 = D["o"].copy()
    o2[:, 0] += 5.0
    m2 = (o2.sum(axis=1, keepdims=True) - o2) / (n - 1)
    L.ident(P, "(a) m_-i does not move with security i's own print", "pathwise, every date", 0.0,
            float(np.abs(m2[:, 0] - D["m"][:, 0]).max()))
    # (b), (c)
    for n in (10, 30, 100, 300):
        beta = rng.uniform(0.5, 1.5, n)
        D = panel_draws(rng, n, max(R // 10, 20_000), beta)
        bbar = (beta.sum() - beta) / (n - 1)
        VN = 8.0 / (n - 1)
        err = D["m"] - bbar * D["f"]
        rep = np.mean(err ** 2, axis=1)
        L.mc(P, "(b) E[(m_-i - beta_bar_-i f)^2] = V_N", f"N={n}", VN, rep.mean(), rep.std() / math.sqrt(len(rep)))
        rep2 = np.mean(D["m"] ** 2 - (bbar ** 2 + VN), axis=1)
        L.mc(P, "(c) E[m_-i^2] = beta_bar^2 sigma_f^2 + V_N", f"N={n}, mean over i", 0.0, rep2.mean(),
             rep2.std() / math.sqrt(len(rep2)))
        num = np.sum(D["r"] * D["m"], axis=1); den = np.sum(D["m"] ** 2, axis=1)
        bM = num.sum() / den.sum()
        th = float(np.sum(beta * bbar) / np.sum(bbar ** 2 + VN))
        # delta-method SE of a ratio of means over dates
        z = num - th * den
        se = z.std() / math.sqrt(len(z)) / den.mean()
        L.mc(P, "(c) pooled projection of r on m_-i", f"N={n}", th, bM, se)
        N.put(f"m8-bM-theory-N{n}", th)
    # (d) population decomposition, heterogeneous securities, error correlated with own news
    for rho in (0.0, 0.5, -0.3):
        n = 50
        beta = rng.uniform(0.5, 1.5, n)
        s_z = rng.uniform(1.0, 3.0, n); s_e = rng.uniform(0.5, 3.0, n)
        D = panel_draws(rng, n, max(R // 10, 20_000), beta, s_z=s_z, s_e=s_e, rho_ze=rho)
        num = np.sum(D["o"] * D["r"], axis=1); den = np.sum(D["o"] ** 2, axis=1)
        b = num.sum() / den.sum()
        SI = np.sum(s_z ** 2 + s_e ** 2 + 2 * rho * s_z * s_e)
        bI = np.sum(s_z ** 2 + rho * s_z * s_e) / SI
        mu = np.sum(beta ** 2) / (np.sum(beta ** 2) + SI)
        th = mu + (1 - mu) * bI
        z = num - th * den
        L.mc(P, "(d) b = mu + (1 - mu) b_I", f"N={n}, corr(zeta, eta)={rho}", th, b, z.std() / math.sqrt(len(z)) / den.mean())
    # (d) sample identity with the inclusive mean
    D = panel_draws(rng, 40, 2000, rng.uniform(0.5, 1.5, 40), rho_ze=0.3)
    oM = D["o"].mean(axis=1, keepdims=True) + 0 * D["o"]
    oI = D["o"] - oM
    b = np.sum(D["o"] * D["r"]) / np.sum(D["o"] ** 2)
    mu = np.sum(oM ** 2) / np.sum(D["o"] ** 2)
    bMh = np.sum(oM * D["r"]) / np.sum(oM ** 2); bIh = np.sum(oI * D["r"]) / np.sum(oI ** 2)
    L.ident(P, "(d) sample identity b = mu b_M + (1 - mu) b_I (inclusive mean)", "2,000 dates x 40", b, mu * bMh + (1 - mu) * bIh, tol=1e-10)
    L.ident(P, "(d) the two parts are orthogonal in the sample", "same", 0.0, float(np.sum(oM * oI)) / float(np.sum(D["o"] ** 2)), tol=1e-12)
    # (e) the kernel, pathwise
    w = A2.LAMBDA0
    mm = rng.normal(0, 0.01, 1000)
    stale = pd.DataFrame({"o": 0.0, "c": 0.0, "u": 0.0, "d": 0.0}, index=range(1000))
    A = A2.kernel(stale["o"], stale["c"], stale["u"], stale["d"], pd.Series(mm))
    L.ident(P, "(e) stale bar: A = 2 (1 - w) m^2", "1,000 bars", 0.0, float(np.abs(A - 2 * (1 - w) * mm ** 2).max()), tol=1e-15)
    O = 100 * np.exp(rng.normal(0, 0.01, 1000)); C = O * np.exp(rng.normal(0, 0.01, 1000))
    H = np.maximum(O, C) * np.exp(np.abs(rng.normal(0, 0.004, 1000)) + 1e-6)
    Lo = np.minimum(O, C) * np.exp(-np.abs(rng.normal(0, 0.004, 1000)) - 1e-6)
    co = AN.bar_coordinates(O, H, Lo, C, np.full(1000, 100.0))
    zero = pd.Series(0.0, index=co.index)
    eo = A2.effective_open(co["o"], pd.Series(0, index=co.index), "panel")
    A_ = A2.kernel(co["o"], co["c"], co["u"], co["d"], eo)
    A0 = AN.kernel(co["o"], co["c"], co["u"], co["d"], zero)
    L.ident(P, "(e) open moved: A equals the open-free kernel", "1,000 bars with a range", 0.0,
            float(np.abs(A_ - A0).max() / A0.max()), tol=1e-12)
    # (f) lambda_n
    prev = 0.0
    for n_obs in (1, 2, 5, 20, 200, 2000):
        lam, se = lambda_n(rng, n_obs, R if n_obs < 200 else R // 4)
        if n_obs == 1:
            L.mc(P, "(f) lambda_1 = 1", "single observation", 1.0, lam, se)
        L.holds(P, f"(f) lambda_n increases (n={n_obs})", "Monte Carlo", lam, prev, lam > prev - 4 * se,
                "value > previous - 4 SE")
        L.holds(P, f"(f) lambda_n < 4 ln 2 (n={n_obs})", "Monte Carlo", lam, 4 * LN2, lam < 4 * LN2 + 4 * se,
                "value < 4 ln 2 + 4 SE")
        N.put(f"m8-lambda-{n_obs}", lam, nd=2)
        prev = lam
    N.put("m8-fourln2", 4 * LN2, nd=2)


def part_b(N: Numbers) -> pd.DataFrame:
    s47 = _load("s47_for_54", "47_corrected_evaluation.py")
    rows = []
    for name in ["NEPSE", "DSE 2023-2026", "DSE 2009-2021", "Vietnam 2007-2020", "Morocco 2012-2026", "Pakistan 2016-2026"]:
        if name != "NEPSE" and not s47.INPUTS.exists():
            continue
        if name == "Pakistan 2016-2026" and not (s47.INPUTS / "psx").exists():
            continue
        S = s47.load(name)
        d = S["d"]
        tr = S["train"].reindex(d.index).fillna(False).astype(bool)
        x = d[tr & d[["o", "c", "u", "d", "r"]].notna().all(axis=1)].copy()
        g = x.groupby("date")["o"]
        x["oM"] = g.transform("mean")
        x["oI"] = x["o"] - x["oM"]
        x["m"] = A2.market_move(x["o"], x["date"])
        n_on = g.transform("size")
        # sampling variance of the leave-one-out mean, from the date's cross-sectional dispersion
        var_o = g.transform("var")
        x["VN"] = var_o / (n_on - 1)
        b = float((x["o"] * x["r"]).sum() / (x["o"] ** 2).sum())
        bM = float((x["oM"] * x["r"]).sum() / (x["oM"] ** 2).sum())
        bI = float((x["oI"] * x["r"]).sum() / (x["oI"] ** 2).sum())
        mu = float((x["oM"] ** 2).sum() / (x["o"] ** 2).sum())
        bLOO = float((x["m"] * x["r"]).sum() / (x["m"] ** 2).sum())
        att = 1.0 - float(x["VN"].sum() / (x["m"] ** 2).sum())
        row = dict(sample=name, seen=name != "Pakistan 2016-2026", bars=len(x),
                   securities_per_date=float(n_on.median()), b=b, b_M=bM, b_I=bI, mu=mu,
                   identity_gap=b - (mu * bM + (1 - mu) * bI), b_M_loo=bLOO, predicted_attenuation=att,
                   stale_open_share=float((x["o"].abs() < A2.EPS).mean()),
                   one_price_share=float(((x["u"] - x["d"]).abs() < A2.EPS).mean()))
        rows.append(row)
        key = {"NEPSE": "NEPSE", "DSE 2023-2026": "DSEa", "DSE 2009-2021": "DSEb", "Vietnam 2007-2020": "VN",
               "Morocco 2012-2026": "MA", "Pakistan 2016-2026": "PK"}[name]
        for k in ("b", "b_M", "b_I", "b_M_loo", "predicted_attenuation"):
            N.put(f"m8-{key}-{k.replace('_', '')}", row[k], nd=2)
        N.put(f"m8-{key}-mu", row["mu"], nd=0, pct=True)
        N.put(f"m8-{key}-stale", row["stale_open_share"], nd=0, pct=True)
        N.put(f"m8-{key}-oneprice", row["one_price_share"], nd=0, pct=True)
        N.put(f"m8-{key}-n", row["securities_per_date"], nd=0)
        print(f"  {name}: b {b:.3f} = {mu:.3f} x {bM:.3f} + {1 - mu:.3f} x {bI:.3f} (gap {row['identity_gap']:.1e}); "
              f"LOO b_M {bLOO:.3f}, predicted attenuation {att:.3f}", flush=True)
    B = pd.DataFrame(rows)
    seen = B[B.seen]
    N.put("m8-bM-min", seen["b_M"].min(), nd=2); N.put("m8-bM-max", seen["b_M"].max(), nd=2)
    N.put("m8-bI-min", seen["b_I"].min(), nd=2); N.put("m8-bI-max", seen["b_I"].max(), nd=2)
    N.put("m8-mu-min", seen["mu"].min(), nd=0, pct=True); N.put("m8-mu-max", seen["mu"].max(), nd=0, pct=True)
    mant, ex = f"{float(B['identity_gap'].abs().max()):.0e}".split("e")
    N.put("m8-gap-max", r"\ensuremath{" + mant + r"\times10^{" + str(int(ex)) + "}}")
    return B


def write_table(B: pd.DataFrame) -> None:
    lab = {"NEPSE": "NEPSE", "DSE 2023-2026": "Dhaka 2023--2026", "DSE 2009-2021": "Dhaka 2009--2021",
           "Vietnam 2007-2020": "Vietnam 2007--2020", "Morocco 2012-2026": "Morocco 2012--2026",
           "Pakistan 2016-2026": "Pakistan 2016--2026$^\\dagger$"}
    lines = []
    for r in B.itertuples():
        lines.append(f"{lab[r.sample]} & {r.securities_per_date:.0f} & {r.b:.3f} & {r.b_M:.3f} & {r.b_I:.3f} & "
                     f"{100 * r.mu:.1f}\\% & {r.b_M_loo:.3f} & {r.predicted_attenuation:.3f} & "
                     f"{100 * r.stale_open_share:.1f}\\% & {100 * r.one_price_share:.1f}\\% \\\\")
    (GEN / "tab_market_open.tex").write_text("\n".join(lines) + "\n")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--quick", action="store_true")
    a = ap.parse_args()
    rng = np.random.default_rng(SEED)
    R = 40_000 if a.quick else 200_000
    t0 = time.time()
    L, N = Ledger(), Numbers()
    part_a(L, N, R, rng)
    led = L.frame()
    led.to_csv(TAB / ("table143_theory_market_open_checks.csv" if not a.quick else "table143_quick.csv"),
               index=False, float_format=FLOAT_FMT)
    N.put("m8-checks-n", str(len(led)))
    N.put("m8-checks-pass", str(int(led["pass"].sum())))
    print(f"  Part A: {len(led)} checks, {int(led['pass'].sum())} pass ({time.time() - t0:.0f}s)")
    fails = led[~led["pass"]]
    if len(fails):
        print(fails[["check", "design", "theory", "value", "se"]].to_string(index=False))
    if not a.quick:
        B = part_b(N)
        B.to_csv(TAB / "table144_theory_market_open_data.csv", index=False, float_format=FLOAT_FMT)
        write_table(B)
        N.write(GEN / "market_open.tex")
        print(B.round(3).to_string(index=False))


if __name__ == "__main__":
    main()
